name: auto-release.yml
on:
  push:
    tags:
      - 'v0.*'
      - '0.*'


jobs:
  create_release:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Create Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: ${{ github.ref_name }}
    permissions:
      packages: write
      contents: write
