name: auto-release.yml
on:
  push:
    tags:
      - 'v0.*'
      - '0.*'
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set tag env var
        run: |
          RELEASE_VERSION=${RELEASE_VERSION:- $(git describe --tags | sed 's/^v//')}
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
      - name: Create Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: ${{ RELEASE_VERSION }}
    permissions:
      packages: write
      contents: write
